/**
 * Tipo enumerado que contiene valores estandarizados de los principales fabricantes
 * de componentes de ordenadores y periféricos.
 *
 * @author : Juan Pablo García Plaza Pérez - Jose Ángel Concha Carrasco
 * @grupo : Wild True
 * Entrega : EC1
 * Curso : 2º GIIIS (Grupo A)
 */

public enum FABRICANTES {
    ACER,
    AMD,
    AOC,
    AMAZON,
    ASROCK,
    ASUS,
    BEHRINGER,
    BENQ,
    BQ,
    CHERRY,
    COOLERMASTER,
    CORSAIR,
    CREATIVE,
    DELL,
    DXRACER,
    EVGA,
    GSKILL,
    GIGABYTE,
    GOOGLE,
    HP,
    HUAWEI,
    HYPERX,
    INTEL,
    KENSINGTON,
    LG,
    LOGITECH,
    MICROSOFT,
    MSI,
    NEWSKILL,
    NOCTUA,
    NINTENDO,
    NVIDIA,
    NZXT,
    OWLOTECH,
    PALIT,
    PHANTEKS,
    PHILIPS,
    RACER,
    SAMSUNG,
    SANDISK,
    SAPPHIRE,
    SEAGATE,
    SEASONIC,
    SENNHEISER,
    SILVERSTONE,
    STEELSERIES,
    TACENS,
    THERMALTAKE,
    TPLINK,
    TRANSCEND,
    TRITTON,
    TRUST,
    VIEWSONIC,
    WACOM,
    WESTERNDIGITAL,
    ZOTAC,
    ZOWIE,
}